## Basic Configuration
title: "0xReki's Adventures by Night"
description: "Creative Writing, Mahjong and more!"

url: "https://0xreki.github.io/crystaldown"
static_url: ''

permalink: pretty
future: true

### Copyright
copyright:
  license: <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a>
  name: Thai “0xReki” Chung
  url: https://0xreki.de/about-me/

# Comments
comments:
  action: /thanks-for-commenting/

### SASS
sass:
  style: compressed
  cache: false

### Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-last-modified-at

remote_theme: 0xReki/crystaldown-theme

## SEO
canonical_domain: https://0xreki.de

patreon:
  title: Become a Patron to get early access to new chapters
  url: https://www.patreon.com/RWNS

# Optimizations
compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false
  startings: [html, head, body]

preload:
  fonts:
  - /assets/fonts/Cardo-Regular.woff2
  - /assets/fonts/Cardo-Bold.woff2
  - /assets/fonts/Source-Sans-Pro-Regular.woff2
  - /assets/fonts/Source-Sans-Pro-Bold.woff2

liquid:
  error_mode: warn

# Syntax
markdown: kramdown

## Defaults
defaults:
  - # /_posts
    scope:
      path: "_posts"
    values:
      category: crystaldown
      layout: 2020/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      image: /assets/images/site-og.png
      comments: true
      commenting: open
      published: true
      image: /assets/images/site-og.png
      permalink: /:year/:month-:day-:title/
  